from typing import Optional
from sqlalchemy import select, update, delete
from src.shared.value_objects.language import Language
from src.shared.value_objects.user_id import UserId
from src.shared.enum import UserProvider
from core.models import Users as User  # SQLAlchemy model
from src.user.infrastructure.models import User as UserModel
from src.user.application.repository.contracts import IUserRepository
from src.user.domain.contracts import IUser  # Interface or Base class
from uuid import UUID
from sqlalchemy.ext.asyncio import AsyncSession


class UserRepository(IUserRepository):
    def __init__(self, model=User, session: AsyncSession = None):
        self.model = model
        self.session = session

    async def find_by_id(self, user_id: UserId) -> IUser:
        stmt = select(self.model).where(self.model.id == str(user_id))
        result = await self.session.execute(stmt)
        user = result.scalar_one_or_none()
        if not user:
            raise ValueError(f"User with ID {user_id} not found")
        return UserModel(
            id=user.id if isinstance(user.id, UUID) else UUID(str(user.id)),
            name=user.name,
            email=user.email,
            password=user.password,
            profile_completed=user.profile_completed,
            user_language=Language(user.user_language),
            learning_language=Language(user.learning_language),
        )

    async def find_by_email(self, email: str) -> Optional[IUser]:
        stmt = select(self.model).where(self.model.email == email)
        result = await self.session.execute(stmt)
        user = result.scalar_one_or_none()
        if not user:
            return None
        return UserModel(
            id=user.id if isinstance(user.id, UUID) else UUID(str(user.id)),
            name=user.name,
            email=user.email,
            password=user.password,
            profile_completed=user.profile_completed,
            user_language=Language(user.user_language),
            learning_language=Language(user.learning_language),
        )

    async def create(self, attributes: dict) -> IUser:
        user = self.model(**attributes)
        self.session.add(user)
        await self.session.flush()  # flush to get autogenerated fields
        return user

    async def delete(self, user_id: UserId) -> None:
        stmt = delete(self.model).where(self.model.id == str(user_id))
        await self.session.execute(stmt)

    async def exists_by_provider(self, provider_id: str, provider: UserProvider) -> bool:
        stmt = (
            select(self.model)
            .where(self.model.provider_id == provider_id)
            .where(self.model.provider_type == provider)
        )
        result = await self.session.execute(stmt)
        return result.scalar_one_or_none() is not None

    async def find_by_provider(self, provider_id: str, provider: UserProvider) -> IUser:
        stmt = (
            select(self.model)
            .where(self.model.provider_id == provider_id)
            .where(self.model.provider_type == provider)
        )
        result = await self.session.execute(stmt)
        user = result.scalar_one_or_none()
        if not user:
            raise ValueError(
                f"User with provider_id {provider_id} and provider {provider.value} not found"
            )
        return UserModel(
            id=user.id if isinstance(user.id, UUID) else UUID(str(user.id)),
            name=user.name,
            email=user.email,
            password=user.password,
            profile_completed=user.profile_completed,
            user_language=Language(user.user_language),
            learning_language=Language(user.learning_language),
        )

    async def update(self, user: IUser) -> None:
        stmt = (
            update(self.model)
            .where(self.model.id == str(user.get_id()))
            .values(
                email=user.get_email(),
                name=user.get_name(),
                password=user.get_password(),
                user_language=user.get_user_language().get_value(),
                learning_language=user.get_learning_language().get_value(),
                profile_completed=user.profile_completed(),
            )
        )
        await self.session.execute(stmt)
